//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod aliment_per_donation;
pub mod aliments;
pub mod beneficiary;
pub mod credentials;
pub mod donation;
pub mod donator;
pub mod post;
pub mod sea_orm_active_enums;
